spring.application.name=payment-api

# ==========================================
# SERVER
# ==========================================
server.port=8080

# ==========================================
# POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# JWT
# ==========================================
jwt.secret=${JWT_SECRET:}
jwt.expiration=86400000

# ==========================================
# STRIPE
# ==========================================
stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.security=INFO
logging.level.com.example.payment_api=INFO